namespace WinThumbsPreloader
{
    partial class AboutForm
    {
        /// <summary>
        /// Required constructor variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Release all used resources.
        /// </summary>
        /// <param name="disposing"> true if the managed resource is to be deleted; otherwise false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Code automatically generated by Windows Form Designer

        /// <summary>
        /// Required method for constructor support - do not
        /// modify the contents of this method using a code editor.
        /// </summary>
        private void InitializeComponent()
        {
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(AboutForm));
            this.CloseButton = new System.Windows.Forms.Button();
            this.LicenceButton = new System.Windows.Forms.Button();
            this.BorderBottom = new System.Windows.Forms.Label();
            this.BottomPanel = new System.Windows.Forms.Panel();
            this.NextButton = new System.Windows.Forms.Button();
            this.BorderTop = new System.Windows.Forms.Label();
            this.HeaderPanel = new System.Windows.Forms.Panel();
            this.AppIconPictureBox = new System.Windows.Forms.PictureBox();
            this.UpdateLabel = new System.Windows.Forms.Label();
            this.AppNameLabel = new System.Windows.Forms.Label();
            this.ContentPanel = new System.Windows.Forms.Panel();
            this.RichTextBox = new System.Windows.Forms.RichTextBox();
            this.BottomPanel.SuspendLayout();
            this.HeaderPanel.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.AppIconPictureBox)).BeginInit();
            this.ContentPanel.SuspendLayout();
            this.SuspendLayout();
            // 
            // CloseButton
            // 
            resources.ApplyResources(this.CloseButton, "CloseButton");
            this.CloseButton.Name = "CloseButton";
            this.CloseButton.UseVisualStyleBackColor = true;
            this.CloseButton.Click += new System.EventHandler(this.CloseButton_Click);
            // 
            // LicenceButton
            // 
            resources.ApplyResources(this.LicenceButton, "LicenceButton");
            this.LicenceButton.Name = "LicenceButton";
            this.LicenceButton.UseVisualStyleBackColor = true;
            this.LicenceButton.Click += new System.EventHandler(this.LicenceButton_Click);
            // 
            // BorderBottom
            // 
            this.BorderBottom.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(223)))), ((int)(((byte)(223)))), ((int)(((byte)(223)))));
            resources.ApplyResources(this.BorderBottom, "BorderBottom");
            this.BorderBottom.Name = "BorderBottom";
            // 
            // BottomPanel
            // 
            this.BottomPanel.BackColor = System.Drawing.SystemColors.Control;
            this.BottomPanel.Controls.Add(this.NextButton);
            this.BottomPanel.Controls.Add(this.CloseButton);
            this.BottomPanel.Controls.Add(this.LicenceButton);
            resources.ApplyResources(this.BottomPanel, "BottomPanel");
            this.BottomPanel.Name = "BottomPanel";
            // 
            // NextButton
            // 
            resources.ApplyResources(this.NextButton, "NextButton");
            this.NextButton.Name = "NextButton";
            this.NextButton.UseVisualStyleBackColor = true;
            this.NextButton.Click += new System.EventHandler(this.NextButton_Click);
            // 
            // BorderTop
            // 
            this.BorderTop.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(223)))), ((int)(((byte)(223)))), ((int)(((byte)(223)))));
            resources.ApplyResources(this.BorderTop, "BorderTop");
            this.BorderTop.Name = "BorderTop";
            // 
            // HeaderPanel
            // 
            this.HeaderPanel.BackColor = System.Drawing.SystemColors.Window;
            this.HeaderPanel.Controls.Add(this.AppIconPictureBox);
            this.HeaderPanel.Controls.Add(this.UpdateLabel);
            this.HeaderPanel.Controls.Add(this.AppNameLabel);
            resources.ApplyResources(this.HeaderPanel, "HeaderPanel");
            this.HeaderPanel.Name = "HeaderPanel";
            // 
            // AppIconPictureBox
            // 
            resources.ApplyResources(this.AppIconPictureBox, "AppIconPictureBox");
            this.AppIconPictureBox.Name = "AppIconPictureBox";
            this.AppIconPictureBox.TabStop = false;
            // 
            // UpdateLabel
            // 
            resources.ApplyResources(this.UpdateLabel, "UpdateLabel");
            this.UpdateLabel.ForeColor = System.Drawing.SystemColors.ControlDarkDark;
            this.UpdateLabel.Name = "UpdateLabel";
            this.UpdateLabel.Click += new System.EventHandler(this.UpdateLabel_Click);
            // 
            // AppNameLabel
            // 
            resources.ApplyResources(this.AppNameLabel, "AppNameLabel");
            this.AppNameLabel.Name = "AppNameLabel";
            // 
            // ContentPanel
            // 
            this.ContentPanel.Controls.Add(this.RichTextBox);
            resources.ApplyResources(this.ContentPanel, "ContentPanel");
            this.ContentPanel.Name = "ContentPanel";
            // 
            // RichTextBox
            // 
            this.RichTextBox.BackColor = System.Drawing.Color.White;
            this.RichTextBox.BorderStyle = System.Windows.Forms.BorderStyle.None;
            resources.ApplyResources(this.RichTextBox, "RichTextBox");
            this.RichTextBox.Name = "RichTextBox";
            this.RichTextBox.ReadOnly = true;
            this.RichTextBox.ShortcutsEnabled = false;
            this.RichTextBox.TabStop = false;
            this.RichTextBox.LinkClicked += new System.Windows.Forms.LinkClickedEventHandler(this.RichTextBox_LinkClicked);
            // 
            // AboutForm
            // 
            resources.ApplyResources(this, "$this");
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.BackColor = System.Drawing.Color.White;
            this.Controls.Add(this.ContentPanel);
            this.Controls.Add(this.BorderTop);
            this.Controls.Add(this.BorderBottom);
            this.Controls.Add(this.BottomPanel);
            this.Controls.Add(this.HeaderPanel);
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.FixedSingle;
            this.MaximizeBox = false;
            this.Name = "AboutForm";
            this.Load += new System.EventHandler(this.AboutForm_Load);
            this.BottomPanel.ResumeLayout(false);
            this.HeaderPanel.ResumeLayout(false);
            this.HeaderPanel.PerformLayout();
            ((System.ComponentModel.ISupportInitialize)(this.AppIconPictureBox)).EndInit();
            this.ContentPanel.ResumeLayout(false);
            this.ResumeLayout(false);

        }

        #endregion
        private System.Windows.Forms.Button CloseButton;
        private System.Windows.Forms.Button LicenceButton;
        private System.Windows.Forms.Label BorderBottom;
        private System.Windows.Forms.Panel BottomPanel;
        private System.Windows.Forms.Label BorderTop;
        private System.Windows.Forms.Panel HeaderPanel;
        private System.Windows.Forms.PictureBox AppIconPictureBox;
        private System.Windows.Forms.Label AppNameLabel;
        private System.Windows.Forms.Panel ContentPanel;
        private System.Windows.Forms.RichTextBox RichTextBox;
        private System.Windows.Forms.Label UpdateLabel;
        private Button NextButton;
    }
}

