global using System;
global using System.Collections.Generic;
global using System.IO;
global using System.Linq;
global using System.Threading.Tasks;
global using System.Windows.Forms;
global using System.Runtime.InteropServices;
global using WinThumbsPreloader.Properties;
global using System.Drawing;