//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WinThumbsPreloader.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WinThumbsPreloader.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WinThumbsPreloader is up to date.
        /// </summary>
        internal static string AboutForm_WinThumbsPreloader_IsUpToDate {
            get {
                return ResourceManager.GetString("AboutForm_WinThumbsPreloader_IsUpToDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A newer version of WinThumbsPreloader is available.
        /// </summary>
        internal static string AboutForm_WinThumbsPreloader_NewVersionAvailable {
            get {
                return ResourceManager.GetString("AboutForm_WinThumbsPreloader_NewVersionAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update check failed.
        /// </summary>
        internal static string AboutForm_WinThumbsPreloader_UpdateCheckFailed {
            get {
                return ResourceManager.GetString("AboutForm_WinThumbsPreloader_UpdateCheckFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon MainIcon {
            get {
                object obj = ResourceManager.GetObject("MainIcon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculating number of items....
        /// </summary>
        internal static string ThumbnailsPreloader_CalculatingNumberOfItems {
            get {
                return ResourceManager.GetString("ThumbnailsPreloader_CalculatingNumberOfItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please wait while the operation is cancelled.
        /// </summary>
        internal static string ThumbnailsPreloader_CancelMessage {
            get {
                return ResourceManager.GetString("ThumbnailsPreloader_CancelMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discovered {0:N0} items.
        /// </summary>
        internal static string ThumbnailsPreloader_Discovered0Items {
            get {
                return ResourceManager.GetString("ThumbnailsPreloader_Discovered0Items", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Items remaining: {0:N0}.
        /// </summary>
        internal static string ThumbnailsPreloader_ItemsRemaining {
            get {
                return ResourceManager.GetString("ThumbnailsPreloader_ItemsRemaining", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string ThumbnailsPreloader_Name {
            get {
                return ResourceManager.GetString("ThumbnailsPreloader_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preloading thumbnails.
        /// </summary>
        internal static string ThumbnailsPreloader_PreloadingThumbnails {
            get {
                return ResourceManager.GetString("ThumbnailsPreloader_PreloadingThumbnails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preloading thumbnails for {0:N0} items.
        /// </summary>
        internal static string ThumbnailsPreloader_PreloadingThumbnailsFor0Items {
            get {
                return ResourceManager.GetString("ThumbnailsPreloader_PreloadingThumbnailsFor0Items", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing: {0}%.
        /// </summary>
        internal static string ThumbnailsPreloader_Processing {
            get {
                return ResourceManager.GetString("ThumbnailsPreloader_Processing", resourceCulture);
            }
        }
    }
}
