//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WinThumbsPreloader.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WinThumbsPreloader.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на WinThumbsPreloader is up to date.
        /// </summary>
        internal static string AboutForm_WinThumbsPreloader_IsUpToDate {
            get {
                return ResourceManager.GetString("AboutForm_WinThumbsPreloader_IsUpToDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на A newer version of WinThumbsPreloader is available.
        /// </summary>
        internal static string AboutForm_WinThumbsPreloader_NewVersionAvailable {
            get {
                return ResourceManager.GetString("AboutForm_WinThumbsPreloader_NewVersionAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Update check failed.
        /// </summary>
        internal static string AboutForm_WinThumbsPreloader_UpdateCheckFailed {
            get {
                return ResourceManager.GetString("AboutForm_WinThumbsPreloader_UpdateCheckFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Icon, аналогичного (Значок).
        /// </summary>
        internal static System.Drawing.Icon MainIcon {
            get {
                object obj = ResourceManager.GetObject("MainIcon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Calculating number of items....
        /// </summary>
        internal static string ThumbnailsPreloader_CalculatingNumberOfItems {
            get {
                return ResourceManager.GetString("ThumbnailsPreloader_CalculatingNumberOfItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Please wait while the operation is cancelled.
        /// </summary>
        internal static string ThumbnailsPreloader_CancelMessage {
            get {
                return ResourceManager.GetString("ThumbnailsPreloader_CancelMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Discovered {0:N0} items.
        /// </summary>
        internal static string ThumbnailsPreloader_Discovered0Items {
            get {
                return ResourceManager.GetString("ThumbnailsPreloader_Discovered0Items", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Items remaining: {0:N0}.
        /// </summary>
        internal static string ThumbnailsPreloader_ItemsRemaining {
            get {
                return ResourceManager.GetString("ThumbnailsPreloader_ItemsRemaining", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Name.
        /// </summary>
        internal static string ThumbnailsPreloader_Name {
            get {
                return ResourceManager.GetString("ThumbnailsPreloader_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Preloading thumbnails.
        /// </summary>
        internal static string ThumbnailsPreloader_PreloadingThumbnails {
            get {
                return ResourceManager.GetString("ThumbnailsPreloader_PreloadingThumbnails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Preloading thumbnails for {0:N0} items.
        /// </summary>
        internal static string ThumbnailsPreloader_PreloadingThumbnailsFor0Items {
            get {
                return ResourceManager.GetString("ThumbnailsPreloader_PreloadingThumbnailsFor0Items", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Processing: {0}%.
        /// </summary>
        internal static string ThumbnailsPreloader_Processing {
            get {
                return ResourceManager.GetString("ThumbnailsPreloader_Processing", resourceCulture);
            }
        }
    }
}
